services:
  qualisoft-vitrine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qualisoft-vitrine-prod
    restart: always
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ELITE_URL=https://elite.qualisoft.sn
    networks:
      - qualisoft-network

networks:
  qualisoft-network:
    external: true # 👈 'true' si le réseau existe déjà pour l'Elite MS