services:
  qualisoft-vitrine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qualisoft-vitrine-prod
    restart: always
    ports:
      - "3002:3000" # Mappe le port 80 du serveur vers le port 3000 du conteneur (Remplacement de l'ancien site)
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ELITE_URL=https://elite.qualisoft.sn
    networks:
      - qualisoft-network

networks:
  qualisoft-network:
    driver: bridge